type = "webpack"
zone_id = ""
account_id = "7bc207d32aa850eda4572c82058c0009"
route = ""
workers_dev = true
webpack_config = "webpack.config.js"
name = "calculator"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"